### PR TITLE
Mark release 4.12.2

### PR DESCRIPTION
**Pull request by wyrzyk**
https://travis-ci.com/atlassian/infrastructure/builds/109287071

### CODE REVIEW

**Comment by dagguh** [comment]
```
Execution failed for task ':publishMavenJavaPublicationToAtlassian-publicRepository'.
> Failed to publish publication 'mavenJava' to repository 'atlassian-public'
   > Could not GET 'https://packages.atlassian.com/public/com/atlassian/performance/tools/infrastructure/maven-metadata.xml'.
      > Read timed out
```

**Comment by wyrzyk** [comment]
```
* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToAtlassian-publicRepository'.
> Failed to publish publication 'mavenJava' to repository 'atlassian-public'
   > Could not write to resource 'https://maven.atlassian.com/public/com/atlassian/performance/tools/infrastructure/4.12.2/infrastructure-4.12.2.jar'.
      > Could not PUT 'https://maven.atlassian.com/public/com/atlassian/performance/tools/infrastructure/4.12.2/infrastructure-4.12.2.jar'. Received status code 403 from server: Forbidden

```

**Comment by wyrzyk** [comment]
```
* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToAtlassian-publicRepository'.
> Failed to publish publication 'mavenJava' to repository 'atlassian-public'
   > Could not write to resource 'https://maven.atlassian.com/public/com/atlassian/performance/tools/infrastructure/4.12.2/infrastructure-4.12.2.jar'.
      > Could not PUT 'https://maven.atlassian.com/public/com/atlassian/performance/tools/infrastructure/4.12.2/infrastructure-4.12.2.jar'. Received status code 403 from server: Forbidden
```

**Comment by dagguh** [comment]
It might have been released partially. We can burn the version and release 4.12.3.

**Comment by mcmurphy2000** [comment]
https://packages.atlassian.com/maven-public/com/atlassian/performance/tools/infrastructure/4.12.2/

**Comment by wyrzyk** [comment]
> It might have been released partially. We can burn the version and release 4.12.3.

It seems the 4.12.2 release is complete. There are all the files available. I'll test it with aws-infra.

**Pull request merged**
